import { Request, Response } from 'express';
import { supabaseAdmin } from '../config/supabase';
import { validateGrupoSchedule } from '../utils/time-validation';

/**
 * Controller for Grupos CRUD operations
 */

export const getGruposByCarrera = async (req: Request, res: Response) => {
    const { carreraId } = req.params;

    try {
        const { data, error } = await supabaseAdmin
            .from('grupos')
            .select('*')
            .eq('carrera_id', carreraId)
            .order('grado', { ascending: true })
            .order('seccion', { ascending: true });

        if (error) {
            return res.status(500).json({
                status: 'error',
                message: 'Failed to fetch groups',
                details: error.message,
            });
        }

        return res.status(200).json({
            status: 'success',
            data,
        });
    } catch (error) {
        return res.status(500).json({
            status: 'error',
            message: 'Internal server error while fetching groups',
        });
    }
};

export const createGrupo = async (req: Request, res: Response) => {
    const { carreraId } = req.params;
    const { grado, seccion, turno, hora_inicio, hora_fin, duracion_bloque } = req.body;
    const userId = req.user?.id;

    if (!grado || !seccion || !turno) {
        return res.status(400).json({
            status: 'error',
            message: 'Grado, seccion and turno are required',
        });
    }

    const scheduleCheck = validateGrupoSchedule(turno, hora_inicio, hora_fin);
    if (!scheduleCheck.valid) {
        return res.status(400).json({
            status: 'error',
            message: scheduleCheck.message,
        });
    }

    try {
        // 1. Authorization: Check if user is admin of the career
        const { data: roleData, error: roleError } = await supabaseAdmin
            .from('roles_carrera')
            .select('rol')
            .eq('carrera_id', carreraId)
            .eq('user_id', userId)
            .eq('rol', 'admin')
            .single();

        if (roleError || !roleData) {
            return res.status(403).json({
                status: 'error',
                message: 'Forbidden: Only career admins can create groups',
            });
        }

        // 2. Insert the group (nombre is auto-generated by trigger)
        const { data, error } = await supabaseAdmin
            .from('grupos')
            .insert({
                carrera_id: carreraId,
                grado,
                seccion,
                turno,
                hora_inicio: hora_inicio || null,
                hora_fin: hora_fin || null,
                duracion_bloque: duracion_bloque || 50,
            })
            .select()
            .single();

        if (error) {
            return res.status(500).json({
                status: 'error',
                message: 'Failed to create group',
                details: error.message,
            });
        }

        return res.status(201).json({
            status: 'success',
            message: 'Group created successfully',
            data,
        });
    } catch (error) {
        return res.status(500).json({
            status: 'error',
            message: 'Internal server error while creating group',
        });
    }
};

export const updateGrupo = async (req: Request, res: Response) => {
    const { id } = req.params;
    const { grado, seccion, turno, hora_inicio, hora_fin, duracion_bloque } = req.body;
    const userId = req.user?.id;

    if (turno) {
        const scheduleCheck = validateGrupoSchedule(turno, hora_inicio, hora_fin);
        if (!scheduleCheck.valid) {
            return res.status(400).json({
                status: 'error',
                message: scheduleCheck.message,
            });
        }
    }

    try {
        // 1. Find the career of the group
        const { data: grupo, error: fetchError } = await supabaseAdmin
            .from('grupos')
            .select('carrera_id')
            .eq('id', id)
            .single();

        if (fetchError || !grupo) {
            return res.status(404).json({
                status: 'error',
                message: 'Group not found',
            });
        }

        // 2. Authorization: Check if user is admin of the career
        const { data: roleData, error: roleError } = await supabaseAdmin
            .from('roles_carrera')
            .select('rol')
            .eq('carrera_id', grupo.carrera_id)
            .eq('user_id', userId)
            .eq('rol', 'admin')
            .single();

        if (roleError || !roleData) {
            return res.status(403).json({
                status: 'error',
                message: 'Forbidden: Only career admins can update groups',
            });
        }

        // 3. Update the group
        const { data: updatedGrupo, error: updateError } = await supabaseAdmin
            .from('grupos')
            .update({
                grado,
                seccion,
                turno,
                hora_inicio,
                hora_fin,
                duracion_bloque,
                updated_at: new Date().toISOString(),
            })
            .eq('id', id)
            .select()
            .single();

        if (updateError) {
            return res.status(500).json({
                status: 'error',
                message: 'Failed to update group',
                details: updateError.message,
            });
        }

        return res.status(200).json({
            status: 'success',
            message: 'Group updated successfully',
            data: updatedGrupo,
        });
    } catch (error) {
        return res.status(500).json({
            status: 'error',
            message: 'Internal server error while updating group',
        });
    }
};

export const deleteGrupo = async (req: Request, res: Response) => {
    const { id } = req.params;
    const userId = req.user?.id;

    try {
        // 1. Find the career of the group
        const { data: grupo, error: fetchError } = await supabaseAdmin
            .from('grupos')
            .select('carrera_id')
            .eq('id', id)
            .single();

        if (fetchError || !grupo) {
            return res.status(404).json({
                status: 'error',
                message: 'Group not found',
            });
        }

        // 2. Authorization: Check if user is admin of the career
        const { data: roleData, error: roleError } = await supabaseAdmin
            .from('roles_carrera')
            .select('rol')
            .eq('carrera_id', grupo.carrera_id)
            .eq('user_id', userId)
            .eq('rol', 'admin')
            .single();

        if (roleError || !roleData) {
            return res.status(403).json({
                status: 'error',
                message: 'Forbidden: Only career admins can delete groups',
            });
        }

        // 3. Delete the group
        const { error: deleteError } = await supabaseAdmin
            .from('grupos')
            .delete()
            .eq('id', id);

        if (deleteError) {
            return res.status(500).json({
                status: 'error',
                message: 'Failed to delete group',
                details: deleteError.message,
            });
        }

        return res.status(200).json({
            status: 'success',
            message: 'Group deleted successfully',
        });
    } catch (error) {
        return res.status(500).json({
            status: 'error',
            message: 'Internal server error while deleting group',
        });
    }
};
